Fix chat hub and update message entity
Ovsyannikov345/EMS pull request #24
Opened 2024-10-16 14:30 UTC by Ovsyannikov345

2024-10-16 14:51 UTC, Gh0stF1ghter requested changes

2024-10-16 14:51 UTC, Gh0stF1ghter commented on ChatService/ChatService/Hubs/ChatHub.cs
> +    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
Isn't it supposed to be in services.AddAuthentication() DI?

2024-10-16 14:51 UTC, Gh0stF1ghter commented on ChatService/ChatService/Hubs/ChatHub.cs
> +            if (connectionIds == null)
use is operator instead of ==

2024-10-17 08:31 UTC, Gh0stF1ghter approved these changes

2024-10-17 08:48 UTC, VladPristavkin approved these changes

2024-10-17 08:55 UTC, merged